apiVersion: v1
kind: Service
metadata:
  name: react-srv
spec:
  type: NodePort
  selector:
    app: myreactapp
  ports:
    - name: myreactapp
      protocol: TCP
      port: 3000
      targetPort: 3000

